CREATE TABLE USUARIO (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    AP1 VARCHAR2(30) NOT NULL,
    AP2 VARCHAR2(30) NOT NULL,
    CORREO VARCHAR2(50) NOT NULL,
    CONTRASEÑA VARCHAR2(32) NOT NULL
);

CREATE TABLE TLF_USUARIO (
    ID_USUARIO NUMBER(8),
    TLF NUMBER(9),
    PRIMARY KEY (ID_USUARIO, TLF),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE UBICACION (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PAIS VARCHAR2(30) NOT NULL,
    CIUDAD VARCHAR2(30) NOT NULL,
    LOCALIDAD VARCHAR2(30) NOT NULL,
    CALLE VARCHAR2(30) NOT NULL,
    LETRA VARCHAR2(30),
    CP NUMBER(8) NOT NULL,
    NUMERO NUMBER(8)
);

CREATE TABLE CATEGORIA (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    DESCRIPCION VARCHAR2(255)
);

CREATE TABLE ORGANIZADOR (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(30)
);

CREATE TABLE TLF_ORGANIZADOR (
    ID_ORGANIZADOR NUMBER(8),
    TLF NUMBER(8),
    PRIMARY KEY (ID_ORGANIZADOR, TLF),
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID)
);

CREATE TABLE EVENTO (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UBICACION NUMBER(8),
    NOMBRE VARCHAR2(30) NOT NULL,
    FECHA DATE NOT NULL,
    HORA_COMIENZO VARCHAR2(30) NOT NULL,
    DURACION NUMBER(8),
    ESTADO BOOLEAN NOT NULL,
    MODALIDAD VARCHAR2(1) CHECK (MODALIDAD IN ('O', 'P', 'A')) NOT NULL,
    TIPO VARCHAR2(1) CHECK (TIPO IN ('C', 'T', 'A')) NOT NULL,
    ID_ORGANIZADOR NUMBER(8) NOT NULL,
    ID_CATEGORIA NUMBER(8) NOT NULL,
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID),
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(id)
);

CREATE TABLE INSCRIPCION (
    ID_USUARIO NUMBER(8),
    ID_EVENTO NUMBER(8),
    FECHA_INSCRIPCION DATE NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
);