CREATE TABLE USUARIO (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    AP1 VARCHAR2(30),
    AP2 VARCHAR2(30),
    CORREO VARCHAR2(50),
    CONTRASEÑA VARCHAR2(32)
);

CREATE TABLE TLF_USUARIO (
    ID_USUARIO NUMBER(8),
    TLF NUMBER(9),
    PRIMARY KEY (ID_USUARIO, TLF),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE UBICACION (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PAIS VARCHAR2(30),
    CIUDAD VARCHAR2(30),
    LOCALIDAD VARCHAR2(30),
    CALLE VARCHAR2(30),
    LETRA VARCHAR2(30),
    CP NUMBER(8),
    NUMERO NUMBER(8)
);

CREATE TABLE CATEGORIA (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    DESCRIPCION VARCHAR2(255)
);

CREATE TABLE ORGANIZADOR (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(30)
);

CREATE TABLE TLF_ORGANIZADOR (
    ID_ORGANIZADOR NUMBER(8),
    TLF NUMBER(8),
    PRIMARY KEY (ID_ORGANIZADOR, TLF),
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID)
);

CREATE TABLE EVENTO (
    ID NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UBICACION NUMBER(8),
    NOMBRE VARCHAR2(30),
    FECHA DATE,
    HORA_COMIENZO VARCHAR2(30),
    DURACION NUMBER(8),
    ESTADO BOOLEAN,
    MODALIDAD VARCHAR2(30),
    ID_ORGANIZADOR NUMBER(8),
    ID_CATEGORIA NUMBER(8),
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID),
    FOREIGN KEY (ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(id)
);

CREATE TABLE INSCRIPCION (
    ID_USUARIO NUMBER(8),
    ID_EVENTO NUMBER(8),
    FECHA_INSCRIPCION DATE,
    PRIMARY KEY (ID_USUARIO, ID_EVENTO),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID)
);